apiVersion: v1
kind: ReplicationController
metadata:
 name: hwrc
spec:
 replicas: 3
 selector:
  app: hw
 template:
  metadata:
   name: nhw
   labels:
    app: hw
  spec:
   containers:
   - name: chw
     image: sktsadhukha/test1
     ports:
     - containerPort: 3000
