apiVersion: v1
kind : Service
metadata:
 name: nhwsnp
spec:
 type: NodePort
 ports:
 - port: 3000
   targetPort: 3000
   nodePort: 31000
 selector:
  app: hw
---
apiVersion: v1
kind: Service
metadata: 
 name: nhwslb
spec:
 type: LoadBalancer
 ports:
 - port: 4000
   targetPort: 3000
#   nodePort: 32000
 selector:
  app: hw
